version: "3"
services:
  server:
    build: .
    command: python routes.py
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"


  neo4j:
    image: discsports/neo4j-apoc
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_directories_import=import
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
